In [1]:
import torch

In [3]:
character_character_matching_threshold = 4

In [4]:
we = torch.tensor([[6,5,4,3,7],[5,0,0,0,0],[4,0,0,0,2],[3,0,0,0,0],[7,0,2,0,0]])

In [5]:
char_i, char_j = torch.where(
    we
    > character_character_matching_threshold
)

In [8]:
qw = torch.where(
    we
    > character_character_matching_threshold
) 

In [9]:
qw

(tensor([0, 0, 0, 0, 0, 1, 2, 2, 3, 4, 4]),
 tensor([0, 1, 2, 3, 4, 0, 0, 4, 0, 0, 2]))

In [6]:
char_i

tensor([0, 0, 0, 0, 0, 1, 2, 2, 3, 4, 4])

In [7]:
char_j

tensor([0, 1, 2, 3, 4, 0, 0, 4, 0, 0, 2])